### ISSUE TITLE
No Image in Artists will throw an Error

### ISSUE THREAD

**Issue by shivangmedhekar** [Sach24eth/CS_554_Project_Intune#32]
If there is no image for the artist, which is if the images array is empty, it won't be able to read the [0] position and will throw an error. Just fixed it for Search but we might have to look into it for the individual renders Artists, Albums and Playlists

**Comment by tejasraibagi26** [comment]
Will fix this.

**Comment by shivangmedhekar** [comment]
type bh in search, you will get an artist with no image

**Comment by shivangmedhekar** [comment]
Artist name is BharuMusic

**Comment by tejasraibagi26** [comment]
Created a PR that addresses this issue.
