### ISSUE TITLE
All routes are still accessible after user log's out of the app

### ISSUE THREAD

**Issue by Sach24eth** [Sach24eth/CS_554_Project_Intune#40]
Steps to reproduce the error:
1) Login and then logout of the application
2) Manually type the URL in the search bar once you're at the sign-up screen

Most of the pages retrieve no data but the route is still accessible. Can we just re-route to the login page regardless of what URL is passed if the user is not logged in?

**Comment by tejasraibagi26** [comment]
Fixed this.
