### ISSUE TITLE
Spotify player covers part of the chatroom

### ISSUE THREAD

**Issue by sahilnaik** [Sach24eth/CS_554_Project_Intune#42]
Can't access the last chatroom if we got more than 6 genres selected

<img width="897" alt="Screen Shot 2022-05-13 at 3 09 39 PM" src="https://user-images.githubusercontent.com/57396109/168373964-2a69649c-397b-4570-bb34-73bdd852db2f.png">

**Comment by Sach24eth** [comment]
Did we move the chatroom because of this issue?

**Comment by tejasraibagi26** [comment]
Moved to another route
